services:
  db:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mafiagame
      POSTGRES_USER: mafia
      POSTGRES_PASSWORD: zg6SePcEJuyYm2SF9zvkYlIPIWIxkV
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U mafia -d mafiagame
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  backend:
    working_dir: /app
    volumes:
      - ./backend:/app
    build:
      dockerfile: docker/backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - docker/enviroment/backend.env
  ngnix:
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs:/etc/nginx/certs/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_started
volumes:
  db-data:
