name: Python CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: Run Flake8
        run: |
          flake8 .

      - name: Run Black
        run: |
          black --config .black . --check --verbose

      - name: Run Unittests for backend
        run: |
          cd backend
          python -m unittest discover

      - name: Run Unittests for tgBot
        run: |
          cd tgbot
          python -m unittest discover
